[project]
name = "llm-debug-gym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openenv-core>=0.2.3",
    "fastapi",
    "uvicorn",
    "openai",
    "pydantic",
    "python-dotenv"
]
[project.scripts]
server = "server.app:main"